// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF_Project_Forms.Models;

[Index("CourseID", Name = "IX_CourseSessions_CourseID")]
[Index("InstructorID", Name = "IX_CourseSessions_InstructorID")]
public partial class CourseSession
{
    [Key]
    public int Id { get; set; }

    public int? CourseID { get; set; }

    public int InstructorID { get; set; }

    public DateTime Date { get; set; }

    public string Title { get; set; }

    [ForeignKey("CourseID")]
    [InverseProperty("CourseSessions")]
    public virtual Course Course { get; set; }

    [InverseProperty("CourseSession")]
    public virtual ICollection<CourseSessionAttendance> CourseSessionAttendances { get; set; } = new List<CourseSessionAttendance>();

    [ForeignKey("InstructorID")]
    [InverseProperty("CourseSessions")]
    public virtual Instructor Instructor { get; set; }
}