// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF_Project_Forms.Models;

[Index("DepartmentID", Name = "IX_Courses_DepartmentID")]
[Index("InstructorID", Name = "IX_Courses_InstructorID")]
public partial class Course
{
    [Key]
    public int ID { get; set; }

    public int? DepartmentID { get; set; }

    public int? InstructorID { get; set; }

    public int? Duration { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<CourseSession> CourseSessions { get; set; } = new List<CourseSession>();

    [InverseProperty("Course")]
    public virtual ICollection<CourseStudent> CourseStudents { get; set; } = new List<CourseStudent>();

    [ForeignKey("DepartmentID")]
    [InverseProperty("Courses")]
    public virtual Department Department { get; set; }

    [ForeignKey("InstructorID")]
    [InverseProperty("Courses")]
    public virtual Instructor Instructor { get; set; }
}